import assert from 'node:assert/strict';

export async function verifySos(db, { employerId, employerUserId, workerOneId, workerTwoId }) {
  const actor = async (id, role='authenticated') => {
    await db.exec('reset role');
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id ?? '']);
    if (role!=='operator') await db.exec(`set role ${role}`);
  };
  const publish = async (request=crypto.randomUUID(), consent=false, name='Credit test hotel') =>
    (await db.query(`select public.publish_application_shift_with_credit($1,$2,$3,'Konobar','Centar','Private credit address',now()+interval '70 days',now()+interval '70 days 6 hours',8000,1::smallint,'{}'::text[],true,$4) id`, [employerId,request,name,consent])).rows[0].id;
  const grant = async (kind, units=1, minutes=null) => (await db.query(`insert into public.employer_posting_grants(employer_id,kind,source,reference_key,units,expires_at,sos_duration_minutes)
    values($1,$2,'manual',gen_random_uuid(),$3,now()+interval '1 day',$4) returning id`, [employerId,kind,units,minutes])).rows[0].id;
  assert.equal((await db.query('select count(*)::int n from public.shift_sos_promotions')).rows[0].n, 0, 'No invented promotions.');
  assert.equal((await db.query('select require_posting_credit from private.application_pilot_workspaces where employer_id=$1',[employerId])).rows[0].require_posting_credit, false, 'Existing pilot publishing stays available.');
  await actor(employerUserId);
  const pilotPost = await publish();
  assert.equal((await db.query('select count(*)::int n from public.employer_posting_usage where shift_id=$1',[pilotPost])).rows[0].n, 0);
  await actor(null,'operator');
  await db.query('update private.application_pilot_workspaces set require_posting_credit=true where employer_id=$1',[employerId]);
  await actor(employerUserId);
  await assert.rejects(()=>publish(),/Posting credit confirmation required/);
  await assert.rejects(()=>db.query(`select public.publish_application_shift($1,gen_random_uuid(),'Legacy caller','Konobar','Centar','Private address',now()+interval '70 days',now()+interval '70 days 6 hours',8000,1::smallint,'{}'::text[],true)`,[employerId]),/Posting credit confirmation required/,'Old clients cannot bypass credit consent.');
  await assert.rejects(()=>publish(undefined,true),/Standard posting credit required/);
  await actor(null,'operator');
  const standard=await grant('standard_post');
  const sos=await grant('sos_promotion',2,60);
  const beforePosts=(await db.query('select count(*)::int n from public.application_posts')).rows[0].n;
  await actor(employerUserId);
  await assert.rejects(()=>publish(undefined,true,'x'),/Invalid public shift details/);
  assert.equal((await db.query('select remaining_units from public.employer_credit_balances where id=$1',[standard])).rows[0].remaining_units,1,'Failed publish does not debit.');
  const request=crypto.randomUUID();
  const post=await publish(request,true);
  assert.equal(await publish(request,true),post);
  assert.equal((await db.query('select remaining_units from public.employer_credit_balances where id=$1',[standard])).rows[0].remaining_units,0);
  await assert.rejects(()=>publish(undefined,true),/Standard posting credit required/);
  await actor(null,'operator');
  assert.equal((await db.query('select count(*)::int n from public.application_posts')).rows[0].n,beforePosts+1);
  await db.query("insert into public.employer_members(employer_id,user_id,member_role) values($1,$2,'manager')",[employerId,workerTwoId]);
  await actor(workerTwoId);
  assert.equal((await db.query('select can_publish from public.application_posting_terms($1)',[employerId])).rows[0].can_publish,false);
  await assert.rejects(()=>publish(undefined,true),/Billing owner required/);
  const activate=(key=crypto.randomUUID(),credit=sos,minutes=60,confirmed=true,target=post)=>db.query('select public.activate_shift_sos($1,$2,$3,$4,$5) id',[target,credit,key,minutes,confirmed]);
  await assert.rejects(()=>activate(),/Billing owner required/);
  await actor(workerOneId);
  await assert.rejects(()=>activate(),/Not authorized/);
  await actor(employerUserId);
  await assert.rejects(()=>activate(undefined,standard),/SOS credit unavailable/);
  await assert.rejects(()=>activate(undefined,sos,30),/SOS credit unavailable/);
  await assert.rejects(()=>activate(undefined,sos,60,false),/SOS confirmation required/);
  await actor(null,'operator');
  await assert.rejects(()=>grant('standard_post',1,60),/check constraint/);
  const revoked=await grant('sos_promotion',1,60);
  const expired=await grant('sos_promotion',1,60);
  const unspecified=await grant('sos_promotion');
  await db.query('update public.employer_posting_grants set revoked_at=now() where id=$1',[revoked]);
  await db.query("update public.employer_posting_grants set starts_at=now()-interval '2 days',expires_at=now()-interval '1 day' where id=$1",[expired]);
  await actor(employerUserId);
  for (const unavailable of [revoked,expired,unspecified]) await assert.rejects(()=>activate(undefined,unavailable),/SOS credit unavailable/);
  const sosRequest=crypto.randomUUID();
  const promotion=(await activate(sosRequest)).rows[0].id;
  assert.equal((await activate(sosRequest)).rows[0].id,promotion);
  await assert.rejects(()=>activate(sosRequest,sos,60,true,pilotPost),/Credit request mismatch/);
  await assert.rejects(()=>activate(),/SOS already active/);
  assert.equal((await db.query('select remaining_units from public.employer_credit_balances where id=$1',[sos])).rows[0].remaining_units,1,'SOS retry/duplicate consumes only once.');
  await assert.rejects(()=>db.query('update public.shift_sos_promotions set ends_at=now()+interval \'1 year\' where id=$1',[promotion]),/permission denied/);
  await actor(null,'anon');
  const promoted=(await db.query('select * from public.public_shift_feed where shift_id=$1',[post])).rows[0];
  assert.equal(promoted.is_sos,true);
  assert.equal(promoted.pay_cents,8000,'Promotion never changes worker compensation.');
  assert.equal('exact_address' in promoted,false);
  assert.equal('phone' in promoted,false);
  await assert.rejects(()=>db.query('select usage_id from public.shift_sos_promotions'),/permission denied/);
  await assert.rejects(()=>activate(),/permission denied/);
  await actor(null,'operator');
  const snapshot=(await db.query('select pay_cents,base_pay_cents,bonus_cents from public.shifts where id=$1',[post])).rows[0];
  assert.equal(snapshot.pay_cents,8000); assert.equal(snapshot.base_pay_cents,8000); assert.equal(snapshot.bonus_cents,0);
  await db.query("update public.shift_sos_promotions set starts_at=now()-interval '2 hours',ends_at=now()-interval '1 hour' where id=$1",[promotion]);
  await actor(null,'anon');
  assert.equal((await db.query('select is_sos from public.public_shift_feed where shift_id=$1',[post])).rows[0].is_sos,false,'Expiry is evaluated on read, without cron.');
  await actor(employerUserId);
  assert.equal((await activate(sosRequest)).rows[0].id,promotion,'Retrying an expired promotion never starts it again.');
  await activate();
  await assert.rejects(()=>activate(undefined,sos,60,true,pilotPost),/Posting credit exhausted/);
  await db.query('select public.cancel_application_post($1)',[post]);
  await actor(null,'anon');
  assert.equal((await db.query('select shift_id from public.public_shift_feed where shift_id=$1',[post])).rows.length,0,'Cancelled ads cannot retain promoted visibility.');
  await actor(null,'operator');
  assert.equal((await db.query("select count(*)::int n from private.application_events where shift_id=$1 and event='sos_activated'",[post])).rows[0].n,2);
  await db.query('update private.application_pilot_workspaces set require_posting_credit=false where employer_id=$1',[employerId]);
  await db.query('delete from public.employer_members where employer_id=$1 and user_id=$2',[employerId,workerTwoId]);
  await actor(employerUserId);
  await publish();
  await actor(null,'operator');
  console.log('Credits/SOS: pilot compatibility, explicit credit consent, atomic rollback, idempotency, owner-only redemption, no wage changes, public privacy, expiry and cancellation verified');
}
